USE UNIVER;

SELECT g.PROFESSION [Специальность],
	   p.SUBJECT [Дисциплина],
	   avg(p.NOTE) [Средняя оценка]
FROM FACULTY AS f
	 INNER JOIN GROUPS AS g
	 ON f.FACULTY = g.FACULTY
	 INNER JOIN STUDENT AS s
	 ON g.IDGROUP = s.IDGROUP
	 INNER JOIN PROGRESS AS p
	 ON s.IDSTUDENT = p.IDSTUDENT
WHERE f.FACULTY = 'ТОВ'
GROUP BY ROLLUP (f.FACULTY, g.PROFESSION, p.SUBJECT)