USE UNIVER;

SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPE [Тип аудитории],
	   max(AUDITORIUM.AUDITORIUM_CAPACITY) [Максимальная вместимость],
	   min(AUDITORIUM.AUDITORIUM_CAPACITY) [Минимальная вместимость],
	   avg(AUDITORIUM.AUDITORIUM_CAPACITY) [Средняя вместимость],
	   sum(AUDITORIUM.AUDITORIUM_CAPACITY) [Суммарная вместимость],
	   count(AUDITORIUM.AUDITORIUM_CAPACITY) [Количество аудиторий]
FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPE