USE UNIVER;

SELECT FACULTY.FACULTY_NAME [Факультет],
	   PULPIT.PULPIT_NAME [Кафедра], 
	   PROFESSION.PROFESSION_NAME [Специальность],
	   SUBJECT.SUBJECT_NAME [Дисциплина],
	   STUDENT.NAME [Имя студента],
	   PROGRESS.NOTE [Оценка],
	   CASE 
			WHEN (PROGRESS.NOTE = 6) THEN 'шесть'
			WHEN (PROGRESS.NOTE = 7) THEN 'семь'
			WHEN (PROGRESS.NOTE = 8) THEN 'восемь'
			ELSE 'вне диапазона(6-8)'
	   END [Оценка]
FROM 
	 ((((((FACULTY
	 inner join GROUPS on FACULTY.FACULTY = GROUPS.FACULTY) 
	 inner join PROFESSION on FACULTY.FACULTY = PROFESSION.FACULTY)
	 inner join PULPIT on FACULTY.FACULTY = PULPIT.FACULTY)
	 inner join SUBJECT on PULPIT.PULPIT = SUBJECT.PULPIT)
	 inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP)
	 inner join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT) 
WHERE PROGRESS.NOTE between 6 and 8
ORDER BY FACULTY.FACULTY_NAME,
		 PULPIT.PULPIT_NAME,
		 PROFESSION.PROFESSION_NAME,
		 STUDENT.NAME,
		 PROGRESS.NOTE DESC