CREATE VIEW [Аудитории] (AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE) AS
	SELECT AUDITORIUM.AUDITORIUM [Код],
		   AUDITORIUM.AUDITORIUM_NAME [Наименование аудитории],
		   AUDITORIUM.AUDITORIUM_CAPACITY [Вместимость],
		   AUDITORIUM.AUDITORIUM_TYPE [Тип аудитории]
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛК';
GO

SELECT * FROM [Аудитории];

INSERT [Аудитории] VALUES ('999-1', '999-1', 20, 'ЛК')
SELECT * FROM [Аудитории];

UPDATE [Аудитории] SET AUDITORIUM = '222-1' WHERE AUDITORIUM_NAME = '999-1'
SELECT * FROM [Аудитории];

DROP VIEW [Аудитории];