CREATE VIEW [Количество кафедр] AS
	SELECT FACULTY.FACULTY_NAME [Имя факультета],
		   count(PULPIT.PULPIT) [Количество кафедр]
	FROM FACULTY
		 INNER JOIN PULPIT
		 ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY FACULTY.FACULTY_NAME;
GO