-- A --
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRANSACTION
DELETE PROGRESS WHERE SUBJECT = 'สร' AND NOTE = 10;
INSERT PROGRESS VALUES ('สร', 1018, '2022-04-15', 7);
UPDATE PROGRESS SET SUBJECT = 'มฤ' WHERE IDSTUDENT = 1018;
SELECT SUBJECT FROM PROGRESS
	WHERE IDSTUDENT = 1018;
----------------- t1 -----------------
SELECT SUBJECT FROM PROGRESS
	WHERE IDSTUDENT = 1018;
----------------- t2 -----------------

-- B --
BEGIN TRANSACTION
DELETE PROGRESS WHERE SUBJECT = 'มฤ';
INSERT PROGRESS VALUES ('สร', 1018, '2022-04-15', 7);
UPDATE PROGRESS SET SUBJECT = 'มฤ' WHERE IDSTUDENT = 1018;
SELECT SUBJECT FROM PROGRESS
	WHERE IDSTUDENT = 1018;
----------------- t1 -----------------
COMMIT;
SELECT SUBJECT FROM PROGRESS
	WHERE IDSTUDENT = 1018;
----------------- t2 -----------------