BEGIN TRAN -- внешняя
	INSERT PROGRESS VALUES ('ДМ', 1001, '2022-04-15', 10);
	BEGIN TRAN -- внутренняя
		UPDATE STUDENT
			SET NAME = 'ДМ' WHERE IDSTUDENT = 1001;
		COMMIT;
	IF @@TRANCOUNT > 0 ROLLBACK;
SELECT
	(SELECT count(*) FROM STUDENT WHERE IDSTUDENT = 1001) 'Студенты',
	(SELECT count(*) FROM PROGRESS WHERE SUBJECT = 'ДМ') 'Оценки';