USE UNIVER;

SELECT FACULTY.FACULTY_NAME,
	   PULPIT.PULPIT_NAME,
	   PROFESSION.PROFESSION_NAME
FROM FACULTY INNER JOIN PULPIT ON PULPIT.FACULTY = FACULTY.FACULTY,
	 PROFESSION
WHERE PULPIT.FACULTY = FACULTY.FACULTY AND FACULTY.FACULTY = PROFESSION.FACULTY
	  AND
	  PROFESSION.PROFESSION_NAME IN (SELECT PROFESSION.PROFESSION_NAME
				 FROM PROFESSION
				 WHERE(PROFESSION.PROFESSION_NAME LIKE '%технология%'
					OR PROFESSION.PROFESSION_NAME LIKE '%технологии%'));