USE UNIVER;

SELECT FACULTY.FACULTY_NAME,
	   PULPIT.PULPIT_NAME,
	   PROFESSION.PROFESSION_NAME
FROM FACULTY INNER JOIN PULPIT ON PULPIT.FACULTY = FACULTY.FACULTY
			 INNER JOIN PROFESSION ON PROFESSION.FACULTY = FACULTY.FACULTY
WHERE (PROFESSION.PROFESSION_NAME LIKE '%технология%' OR
	   PROFESSION.PROFESSION_NAME LIKE '%технологии%');