USE UNIVER;

SELECT
(
	SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
	WHERE PROGRESS.SUBJECT LIKE 'нюХо'
)[нюХо],
(
	SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
	WHERE PROGRESS.SUBJECT LIKE 'ясад'
)[ясад],
(
	SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
	WHERE PROGRESS.SUBJECT LIKE 'йц'
)[ад]