DECLARE @faculty char(2) = 'ИТ';
SELECT CASE
			WHEN PROGRESS.NOTE BETWEEN 9 AND 10 THEN 'Лучше некуда'
			WHEN PROGRESS.NOTE BETWEEN 7 AND 8 THEN 'Хорошо'
			WHEN PROGRESS.NOTE BETWEEN 4 AND 6 THEN 'Нормально'
			ELSE 'TERRIBLE!'
		END [Оценка],
		count(*) [Количество]
FROM PROGRESS 
	 INNER JOIN STUDENT
	 ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
	 INNER JOIN GROUPS
	 ON STUDENT.IDGROUP = STUDENT.IDGROUP
	 AND GROUPS.FACULTY = @faculty
GROUP BY PROGRESS.NOTE